# Python Basics

This file helps you review basic Python operations. You can learn more details on a free e-book 
https://problemsolvingwithpython.com/

## Lists

In [1]:
an_empty_list = list()
an_empty_list

[]

In [2]:
a_list = [1, 2.3, 'a', True]
a_list

[1, 2.3, 'a', True]

In [3]:
a_list[1] 
# prints 2.3 

2.3

In [4]:
a_list[1] = 2.5
# a_list is now [1, 2.5, 'a', True]
a_list

[1, 2.5, 'a', True]

In [5]:
a_list[1:3]
# prints [2.5, 'a']

[2.5, 'a']

In [6]:
a_list[1:4]

[2.5, 'a', True]

In [7]:
a_list[2:3]

['a']

In [8]:
a_list[::-1] 
# returns the reverse of the list: [True, 'a', 2.3, 1]

[True, 'a', 2.5, 1]

In [9]:
a_list.append(5) 
# a_list is now [1, 2.5, 'a', True, 5]
a_list

[1, 2.5, 'a', True, 5]

In [10]:
len(a_list) 
# prints 5

5

In [11]:
del a_list[0] 
# a_list is now [2.5, 'a', True, 5]
a_list

[2.5, 'a', True, 5]

In [12]:
a_list += [1, 'b'] 
# a_list is now [2.5, 'a', True, 5, 1, 'b']
a_list 

[2.5, 'a', True, 5, 1, 'b']

In [13]:
a, b, c, d, e, f = [2.5, 'a', True, 5, 1, 'b'] 
# a now is 2.5, b is 'a' and so on
a

2.5

## Defining functions

In [15]:
def half(x): 
    return x/2.0

In [16]:
half(10) 

5.0

In [17]:
half(18) 

9.0

In [18]:
half(29) 

14.5

In [19]:
half(12345) 

6172.5

## Numpy

In [20]:
import numpy as np

In [21]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
a.shape

(3, 5)

In [25]:
a.ndim

2

In [26]:
a.size

15

In [27]:
c=np.zeros((3, 4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
d=np.ones((2, 3, 4))
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [29]:
a.min()

0

In [30]:
a.sum()

105

In [31]:
a.max()

14

In [32]:
a[0]

array([0, 1, 2, 3, 4])

In [33]:
a[1]

array([5, 6, 7, 8, 9])

In [34]:
a[2]

array([10, 11, 12, 13, 14])